# Generated by Django 4.1a1 on 2022-12-22 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterModelOptions(
            name='postcomments',
            options={'verbose_name_plural': 'Post Comments'},
        ),
        migrations.AlterModelOptions(
            name='postlikes',
            options={'verbose_name_plural': 'Post Likes'},
        ),
    ]
