# Generated by Django 4.1a1 on 2023-01-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_options_alter_postcomments_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='post_likes',
            field=models.IntegerField(default=0),
        ),
    ]
