# Generated by Django 4.1a1 on 2023-01-17 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='noOfApplicants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobs',
            name='noOfVacancies',
            field=models.IntegerField(default=1),
        ),
    ]
