# Generated by Django 4.1a1 on 2023-01-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobs_noofapplicants_jobs_noofvacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
