# Generated by Django 3.2 on 2023-02-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0008_alter_companyprofile_operatinghours'),
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adImage', models.ImageField(upload_to='ads')),
                ('Ad_text', models.CharField(blank=True, max_length=100)),
                ('adType', models.CharField(choices=[('Banner', 'Banner'), ('Sidebar', 'Sidebar'), ('Footer', 'Footer')], max_length=50)),
                ('adStatus', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=50)),
                ('impressionsCount', models.PositiveIntegerField(default=0)),
                ('clicksCount', models.PositiveIntegerField(default=0)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('companyProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companyprofile')),
            ],
        ),
    ]
