# Generated by Django 4.1a1 on 2022-12-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyimages',
            options={'verbose_name_plural': 'Company Images'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name_plural': 'Company Profiles'},
        ),
        migrations.AlterModelOptions(
            name='follows',
            options={'verbose_name_plural': 'Follows'},
        ),
        migrations.AlterModelOptions(
            name='likes',
            options={'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
