# Generated by Django 4.1a1 on 2023-01-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyprofile_companyreviews_alter_reviews_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='reviewPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
