# Generated by Django 4.1a1 on 2023-01-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_reviews_created_at_reviews_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
