# Generated by Django 4.1a1 on 2023-01-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_alter_reviews_created_at_alter_reviews_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='operatingHours',
            field=models.JSONField(default={'key': 'value'}),
        ),
    ]
